const firstYearStudentesData = [
    {
        id:"1",
        name:"Adam",
        description:"student",     
         profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Present",
        studentDetails:{
            branch:"CSE",
            semester:'2',
        }
    },
    {
        id:"2",
        name:"Mark",
        description:"Tech Team", 
        profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Absent",
        studentDetails:{
            branch:"IT",
            semester:'2',
        }
    },
    {
        id:"3",
        name:"Joe",
        description:"student", 
        profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Absent",
        studentDetails:{
            branch:"Civil",
            semester:'2',
        }
    },
    {
        id:"4",
        name:"John",
        description:"student", 
        profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Present",
        studentDetails:{
            branch:"CSE",
            semester:'2',
        }
    },
    {
        id:"5",
        name:"Lasn",
        description:"ETSA", 
        profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Present",
        studentDetails:{
            branch:"ECE",
            semester:'2',
        }
    },
]
const secondYearStudentesData = [
    {
        id:"1",
        name:"param",
        description:"student",     
         profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Present",
        studentDetails:{
            branch:"CSE",
            semester:'2',
        }
    },
    {
        id:"2",
        name:"Manju",
        description:"Tech Team", 
        profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Absent",
        studentDetails:{
            branch:"Civil",
            semester:'2',
        }
    },
    {
        id:"3",
        name:"Joe Biden",
        description:"Cultural secratory", 
        profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Absent",
        studentDetails:{
            branch:"CSE",
            semester:'2',
        }
    },
    {
        id:"4",
        name:"John",
        description:"student", 
        profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Present",
        studentDetails:{
            branch:"CSE",
            semester:'2',
        }
    },
    {
        id:"5",
        name:"Lakshay",
        description:"ETSA", 
        profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Present",
        studentDetails:{
            branch:"ECE",
            semester:'2',
        }
    },
    {
        id:"6",
        name:"Mitali",
        description:"student", 
        profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Absent",
        studentDetails:{
            branch:"CSE",
            semester:'2',
        }
    },
    {
        id:"7",
        name:"Shalu",
        description:"student", 
        profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Absent",
        studentDetails:{
            branch:"CSE",
            semester:'2',
        }
    },
    {
        id:"8",
        name:"Mohit",
        description:"tech-team", 
        profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Absent",
        studentDetails:{
            branch:"CSE",
            semester:'2',
        }
    },
    {
        id:"9",
        name:"Mridul",
        description:"student", 
        profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Absent",
        studentDetails:{
            branch:"CSE",
            semester:'2',
        }
    },
    {
        id:"10",
        name:"Mayank",
        description:"student", 
        profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Present",
        studentDetails:{
            branch:"CSE",
            semester:'2',
        }
    },
]
const thirdYearStudentesData = [
    {
        id:"1",
        name:"ram",
        description:"student",     
         profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Present",
        studentDetails:{
            branch:"CSE",
            semester:'2',
        }
    },
    {
        id:"2",
        name:"sham",
        description:"Tech Team", 
        profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Absent",
        studentDetails:{
            branch:"IT",
            semester:'2',
        }
    },
    {
        id:"3",
        name:"nikhil",
        description:"student", 
        profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Absent",
        studentDetails:{
            branch:"Civil",
            semester:'2',
        }
    },
    {
        id:"4",
        name:"aman",
        description:"student", 
        profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Present",
        studentDetails:{
            branch:"CSE",
            semester:'2',
        }
    },
    {
        id:"5",
        name:"thakur",
        description:"ETSA", 
        profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Present",
        studentDetails:{
            branch:"ECE",
            semester:'2',
        }
    },
]

const fourthYearStudentesData = [
    {
        id:"1",
        name:"Bhola",
        description:"ETSA President",     
         profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Present",
        studentDetails:{
            branch:"CSE",
            semester:'2',
        }
    },
    {
        id:"2",
        name:"keshav",
        description:"Tech Team", 
        profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Absent",
        studentDetails:{
            branch:"IT",
            semester:'2',
        }
    },
    {
        id:"3",
        name:"mukund",
        description:"student", 
        profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Absent",
        studentDetails:{
            branch:"Civil",
            semester:'2',
        }
    },
    {
        id:"4",
        name:"Johnney",
        description:"ETSA", 
        profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Present",
        studentDetails:{
            branch:"CSE",
            semester:'2',
        }
    },
    {
        id:"5",
        name:"Lasn",
        description:"ETSA", 
        profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Present",
        studentDetails:{
            branch:"ECE",
            semester:'2',
        }
    },
    {
        id:"6",
        name:"Bharat",
        description:"Sports secratory", 
        profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Present",
        studentDetails:{
            branch:"ECE",
            semester:'2',
        }
    },
    {
        id:"7",
        name:"binit",
        description:"student", 
        profilePicUrl:"https://bit.ly/dan-abramov",
        action:"Present",
        studentDetails:{
            branch:"ECE",
            semester:'2',
        }
    },
]

module.exports = {firstYearStudentesData,secondYearStudentesData,thirdYearStudentesData,fourthYearStudentesData};